var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var TranscriptSchema = new Schema(
    {

        GVCN: { type: String },
        tenGV: { type: String },
        soHieu: { type: String },
        idHocSinh: { type: String },
        tenHocSinh: { type: String },
        diemAnh:
        {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },

        diemToan: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemVan: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemSinh: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemSu: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemDia: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemCongNghe: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemLy: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemHoa: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemGDCD: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemTin: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemTheDuc: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },
        diemMyThuat: {
            diem15p: { type: String },
            diem1tiet: { type: String },
            diemGiuaKy1: { type: String },
            diemCuoiKy1: { type: String },
            diem15p2: { type: String },
            diem1tiet2: { type: String },
            diemGiuaKy2: { type: String },
            diemCuoiKy2: { type: String },
        },





    }
);
module.exports = mongoose.model('Transcript', TranscriptSchema)